### ISSUE TITLE
Erro na avaliação com URLs Slugs 

### ISSUE THREAD

**Issue by SergioDiniz** [vinibaggio/colcho.net#5]
ola pessoal, alguem pode me da uma ajudinha aqui?
estou com um problema com o livro Ruby on Rails, colocando sua aplicação web nos trilhos,

ja estou no final do livro, no ultimo capitulo, e me deparei com um problema na utilização de URLs slugs

eu segui o tópico e esta tudo funcionando normal, ou melhor, quase tudo...
o problema é que a função de classificar os quartos, que estava funcionando, agora esta dando erro no javascript por causa do frienly_id

quando eu clico na estrela, o formulário possui o action="/pt-BR/rooms/**casa-com-piscina**/reviews", um exemplo, e com isso diz que ele não acha essa rota

erro no console:
POST http://localhost:3000/pt-BR/rooms/casa-com-piscina/reviews 404 (Not Found)

se eu mudar no html a rota do action, substituindo a texto do friendly_id pelo id, ele funciona, tipo:
action="/pt-BR/rooms/**1**/reviews"

oq eu posso fazer? '--'

essa é a saida no console:

```
ActiveRecord::RecordNotFound (Couldn't find Room with 'id'=casa-com-piscina):
  app/controllers/rooms/reviews_controller.rb:19:in `room'
  app/controllers/rooms/reviews_controller.rb:5:in `create'
  app/controllers/rooms/reviews_controller.rb:13:in `update'
```

**Comment by SergioDiniz** [comment]
opa, acabei de arrumar
tinha esquecido de mudar o método room em reviews_controller para pesquisar usando o firendly.find como no rooms_controller
